import type {Metadata} from "next";
import "./globals.css";
import AuthProvider from "@/views/shared/layout/auth-provider";
import UserContainer from "@/views/shared/layout/user-container";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
                        children,
                    }: Readonly<{
    children: React.ReactNode;
}>) => {

    return (
        <AuthProvider>
            <html lang="ko">
            <body style={{fontFamily: "Pretendard, sans-serif"}}>
            <UserContainer>
                {children}
            </UserContainer>
            </body>
            </html>
        </AuthProvider>
    );
}

export default RootLayout