import type {Metadata} from "next";
import "./globals.css";
import AuthProvider from "@/views/shared/layout/AuthProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <AuthProvider>
            <html lang="ko">
            <body className="min-h-screen flex items-center justify-center font-" style={{fontFamily: "Pretendard, sans-serif"}}>
            {children}
            </body>
            </html>
        </AuthProvider>
    );
}

export default RootLayout